const products = [
    {
    id: 1,
    name: "Sony wired Earphone",
    price: 1060,
    category: "Headphone",
    rating: 4.6,
    image: "/src/img/earphone.png",
  },
  {
    id: 2,
    name: "Canon Printer",
    price: 9850,
    category: "Printer",
    rating: 3.7,
    image: "/src/img/printer.png",
  },
  {
    id: 3,
    name: "Hp Laptop",
    price: 65000,
    category: "Laptop",
    rating: 4.0,
    image: "/src/img/lap1.png",
  },
  {
    id: 4,
    name: "Nikon Camera",
    price: 45499,
    category: "Camera",
    rating: 5.0,
    image: "/src/img/c3.png",
  },
  {
    id: 5,
    name: "Canon Camera",
    price: 50400,
    category: "Camera",
    rating: 4.8,
    image: "/src/img/c1.png",
  },
  {
    id: 6,
    name: "SanDisk Pendrive, 32GB",
    price: 450,
    category: "Pendrive",
    rating: 4.1,
    image: "/src/img/pendrive2.png",
  },
  {
    id: 7,
    name: "SanDisk Pendrive, 128GB",
    price: 980,
    category: "Pendrive",
    rating: 4.7,
    image: "/src/img/pendrive1.png",
  },
  {
    id: 8,
    name: "Sony Laptop",
    price: 60000,
    category: "Laptop",
    rating: 3.8,
    image: "/src/img/Sony_Laptop.png",
  },
  {
    id: 9,
    name: "Lenovo Laptop",
    price: 74000,
    category: "Laptop",
    rating: 4.5,
    image: "/src/img/lap3.png",
  },
  {
    id: 10,
    name: "Headphone",
    price: 1150,
    category: "Headphone",
    rating: 4.2,
    image: "/src/img/headphones.png",
  },
  {
    id: 11,
    name: "Home Theater Speakers",
    price: 34620,
    category: "Speaker",
    rating: 3.2,
    image: "/src/img/Home.png",
  },
  {
    id: 12,
    name: "External Speaker",
    price: 21630,
    category: "Speaker",
    rating: 3.9,
    image: "/src/img/e_speaker.png",
  },
];

export default products;
